jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot_test
  username: root
  password: root
#????????????????????
spring:
  profiles:
    active:  abc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: root
#tomcat????
server:
  port: 80
#??????
logging:
  level:
    com.itcast: debug
    org.springframework: info
